image: alpine:latest

variables:
  KUBERNETES_VERSION: 1.11.7
  HELM_VERSION: 2.12.3

  DOCKER_DRIVER: overlay2

  ROLLOUT_RESOURCE_TYPE: deployment

stages:
  - build
  - test

build:
  script:
    - pwd
    - ls
    - docker ls
    - docker build . --tag plomdockerbuild


test:
  script:
    - pwd
    - ls
    - echo "Hello World"
