# SPDX-License-Identifier: FSFAP
# Copyright (C) 2019 John Hsu
# Copyright (C) 2019-2020 Colin B. Macdonald
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

# This the CI configuration for Plom
#
# TODO list
# ---------
#   * use our Dockerfile instead of apt-get
#       - I think this is "dind"
#   * test on latest versions of deps with Docker pinned on req.txt

image: docker:19.03.11

services:
  - docker:19.03.11-dind

variables:
  DOCKER_DRIVER: overlay2
  IM: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IM_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - static_analysis
  - nodocker
  - build
  - test
  - final


docker-image:
  stage: build
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IM_LATEST || true
    - docker build --cache-from $IM_LATEST --tag $IM .
    - docker push $IM


# Get fast results by running tests in a copy-pasta of the docker-image job
quick-pytests:
  stage: build
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IM_LATEST || true
    - docker build --cache-from $IM_LATEST --tag $IM .
    - docker run $IM pytest-3 -l --pyargs plom


# If we are on the master branch, we tag the above as "latest"
docker-image-master:
  stage: final
  needs: ["docker-image"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IM
    - docker tag $IM $IM_LATEST
    - docker push $IM_LATEST
  only:
    - master


# If we have a tag, then push to PyPIi using TWINE_* env vars
# Debug: `upload -r testpypi`, comment `only`, change and unprotect token
pypi:
  image: $IM
  stage: final
  needs: ["docker-image"]
  cache: {}
  script:
    - python3 -m pip install -U twine wheel setuptools
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine check dist/*
    - python3 -m twine upload dist/*
  only:
    - tags


black:
  stage: static_analysis
  needs: []
  image: "python:3.8"
  before_script:
    - pip3 install "black~=19.10b"
  script:
    - black --check --diff plom
  allow_failure: true


basic:
  stage: test
  needs: ["docker-image"]
  image: $IM
  script:
    - plom-init


unittests:
  stage: test
  needs: ["docker-image"]
  image: $IM
  script:
    - pytest-3 -l --pyargs plom


doctests:
  stage: test
  needs: ["docker-image"]
  image: $IM
  script:
    # TODO: need to recursively do this instead of specifying files
    - python3 -m doctest plom/specParser.py
    - echo "no news is good news"


demoserver:
  stage: test
  needs: ["docker-image"]
  image: $IM
  before_script:
    - apt-get --no-install-recommends --yes install iproute2 psmisc file curl
  script:
    - mkdir demo
    - pushd demo
    - plom-build new --demo
    # Start server
    - ip addr
    - plom-server init
    - plom-server users --demo
    - plom-server launch &
    - sleep 2
    - sleep 2
    - echo "Server should be in background"
    - jobs -l
    - echo "We should be able to connect to it"
    - curl -k https://localhost:41984/Version
    - plom-build class --demo -w 1234
    - plom-build make -w 1234
    - python3 -m plom.produce.faketools -w 1234
    - plom-scan process -w 4567 fake_scribbled_exams1.pdf
    - plom-scan upload -w 4567 fake_scribbled_exams1
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams2.pdf
    - plom-scan upload -w 4567 fake_scribbled_exams2
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams3.pdf
    - plom-scan upload -w 4567 fake_scribbled_exams3
    - plom-scan status -w 4567
    - echo "Now take down the server"
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/2880
    - jobs -l
    - kill %1
    - sleep 2
    - echo "Should be no jobs and this should succeed"
    - jobs -l
    - popd


hwdemoserver:
  stage: test
  needs: ["docker-image"]
  image: $IM
  before_script:
    - apt-get --no-install-recommends --yes install iproute2 psmisc file curl
  script:
    - mkdir demo
    - pushd demo
    - plom-build new --demo
    # Start server
    - ip addr
    - plom-server init
    - plom-server users --demo
    - plom-server launch &
    - sleep 2
    - sleep 2
    - echo "Server should be in background"
    - jobs -l
    - echo "We should be able to connect to it"
    - curl -k https://localhost:41984/Version
    - plom-build class --demo -w 1234
    - plom-build make -w 1234
    - plom-hwscan status -w 4567
    - python3 -m plom.produce.hwFaker -w 1234
    - plom-hwscan allbyq -w 4567 -y
    - plom-hwscan missing -w 4567 -y
    - plom-hwscan submitted -w 4567
    - plom-hwscan submitted -d
    - echo "Now take down the server"
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/2880
    - jobs -l
    - kill %1
    - sleep 2
    - echo "Should be no jobs and this should succeed"
    - jobs -l
    - popd


fullworkflow:
  stage: test
  needs: ["docker-image"]
  image: $IM
  before_script:
    - apt-get --no-install-recommends --yes install iproute2 psmisc file curl
  script:
    # Build tests
    - mkdir play
    - pushd play
    - plom-build new
    - plom-build parse
    - python3 -m plom.produce.demotools
    # TODO: override the private seed
    # sed specAndDatabase/verifiedSpec.toml -i -e "s/privateSeed = .*/privateSeed = \"8253996856355501\"/"
    # diff -u specAndDatabase/verifiedSpec.toml ../tmp/resources/verifiedSpec.toml
    # Start server
    - ip addr
    - plom-server init
    - plom-server users --demo
    - plom-server launch &
    - sleep 2
    - sleep 2
    - echo "Server should be in background"
    - jobs -l
    - echo "We should be able to connect to it"
    - curl -k https://localhost:41984/Version
    - plom-build class --demo -w 1234
    - plom-build make -w 1234
    - A=`ls papersToPrint/ | wc -l`  # How many files?
    - bash -c "[[ $A == 20 ]]"       # should be 20
    # TODO: https://gitlab.math.ubc.ca/andrewr/MLP/issues/695
    - python3 -m plom.produce.faketools -w 1234
    # Scan and upload
    # supposed to fail:
    - if (plom-scan process); then false; else true; fi
    - plom-scan process -w 4567 fake_scribbled_exams1.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams1
    # TODO: I removed some -c lines here...
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams2.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams2
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams3.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams3
    - plom-scan status -w 4567
    ## not supposed to be done yet:
    - if (plom-finish status -w 1234); then false; else true; fi
    - python3 -m plom.client.randoIDer -s localhost -u user0 -w 0123
    - python3 -m plom.client.randoMarker -s localhost -u user0 -w 0123
    - plom-finish status -w 1234
    - plom-finish csv -w 1234
    - A=`cat marks.csv  | wc -l`      # How many lines?
    - bash -c "[[ $A == 20 ]]"        # should be 19 + 1 - since 1 page from 1 test is deleted
    - file -b marks.csv  | grep ASCII   # should be ascii test
    - plom-finish reassemble -w 1234
    - A=`ls reassembled/ | wc -l`    # How many files?
    - bash -c "[[ $A == 19 ]]" # since 1 test incomplete
    - A=`du -sm reassembled/ | cut -f1`  # Don't regress on issue #627
    - bash -c "[[ $A -lt 40 ]]"          # not more than 10 MB
    - plom-finish webpage
    - A=`ls codedReturn/ | wc -l`    # How many files?
    - bash -c "[[ $A == 20 ]]"       # 20-1 pdf + 1 html
    - echo "Now take down the server"
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/2880
    - jobs -l
    - kill %1
    - sleep 2
    - echo "Should be no jobs and this should succeed"
    - jobs -l
    - popd

backgroundTest:
  image: alpine
  stage: static_analysis
  needs: []
  script:
    - sleep 60 &
    - jobs -l
    - jobs -p
    - echo "Sleep job has started"
    - sleep 2
    - jobs -l
    - jobs -p
    - echo "We will kill it"
    - kill -9 %1
    - echo "Should be no jobs and this should succeed"
    - jobs -p

appstreamValid:
  stage: static_analysis
  needs: []
  image: alpine
  before_script:
    - apk add appstream-glib
  script:
    - appstream-util validate-relax org.plomgrading.PlomClient.metainfo.xml


legacy_full:
  stage: nodocker
  needs: []
  image: ubuntu:18.04
  # Need pip >= 19, which turns out to be nontrivial: cannot just call
  # pip/pip3 after upgrading, hence `python3 -m pip` stuff below
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata curl
    - apt-get --no-install-recommends --yes install
      zbar-tools cmake make imagemagick g++ openssl
      python3-passlib python3-pandas python3-pyqt5 python3-pytest
      python3-pyqt5.qtsql python3-pyqrcode python3-png python3-dev
      python3-pip python3-setuptools python3-wheel
      texlive-latex-extra dvipng latexmk texlive-fonts-recommended
      python3-requests-toolbelt python3-tqdm
      libpango-1.0 libpangocairo-1.0 libjpeg-turbo8-dev libturbojpeg0-dev python3-cffi
      iproute2 psmisc file
    # apt-get --no-install-recommends --yes install libimage-exiftool-perl
    - pip3 install --upgrade pip
    - which pip3
    - python3 -m pip -V
    - python3 -m pip install --upgrade setuptools
    - python3 -m pip install packaging
    # Issue #950, tensorflow minimal versions
    - python3 -m pip install numpy==1.16.6
    - python3 -m pip install requests==2.21.0
    # let setup.py deps do their thing
    # python3 -m pip install pymupdf weasyprint peewee toml aiohttp pyzbar
    # not needed until prediction
    # python3 -m pip install imutils lapsolver opencv-python tensorflow
  script:
    - python3 ./setup.py build bdist_wheel
    - pushd dist
    - python3 -m pip install plom-*.whl
    - popd
    # First, run the unit tests
    - pytest-3 -l --pyargs plom
    # Build tests
    - mkdir play
    - pushd play
    - plom-build new
    - plom-build parse
    - python3 -m plom.produce.demotools
    # TODO: override the private seed
    # sed specAndDatabase/verifiedSpec.toml -i -e "s/privateSeed = .*/privateSeed = \"8253996856355501\"/"
    # diff -u specAndDatabase/verifiedSpec.toml ../tmp/resources/verifiedSpec.toml
    # Start server
    - ip addr
    - plom-server init
    - plom-server users --demo
    - plom-server launch &
    - sleep 2
    - sleep 2
    - echo "Server should be in background"
    - jobs -l
    - echo "We should be able to connect to it"
    - curl -k https://localhost:41984/Version
    - plom-build class --demo -w 1234
    - plom-build make -w 1234
    - A=`ls papersToPrint/ | wc -l`  # How many files?
    - bash -c "[[ $A == 20 ]]"       # should be 20
    # TODO: https://gitlab.math.ubc.ca/andrewr/MLP/issues/695
    - python3 -m plom.produce.faketools -w 1234
    # Scan and upload
    # supposed to fail:
    - if (plom-scan process); then false; else true; fi
    - plom-scan process -w 4567 fake_scribbled_exams1.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams1
    # TODO: I removed some -c lines here...
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams2.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams2
    - plom-scan status -w 4567
    - plom-scan process -w 4567 fake_scribbled_exams3.pdf
    - plom-scan upload -w 4567 -u fake_scribbled_exams3
    - plom-scan status -w 4567
    ## not supposed to be done yet:
    - if (plom-finish status -w 1234); then false; else true; fi
    - python3 -m plom.client.randoIDer -s localhost -u user0 -w 0123
    - python3 -m plom.client.randoMarker -s localhost -u user0 -w 0123
    - plom-finish status -w 1234
    - plom-finish csv -w 1234
    - A=`cat marks.csv  | wc -l`      # How many lines?
    - bash -c "[[ $A == 20 ]]"        # should be 19 + 1 - since 1 page from 1 test is deleted
    - file -b marks.csv  | grep ASCII   # should be ascii test
    - plom-finish reassemble -w 1234
    - A=`ls reassembled/ | wc -l`    # How many files?
    - bash -c "[[ $A == 19 ]]" # since 1 test incomplete
    - A=`du -sm reassembled/ | cut -f1`  # Don't regress on issue #627
    - bash -c "[[ $A -lt 40 ]]"          # not more than 10 MB
    - plom-finish webpage
    - A=`ls codedReturn/ | wc -l`    # How many files?
    - bash -c "[[ $A == 20 ]]"       # 20-1 pdf + 1 html
    - echo "Now take down the server"
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/2880
    - jobs -l
    - kill %1
    - sleep 2
    - echo "Should be no jobs and this should succeed"
    - jobs -l
    - popd


# this one is built from our official docker image
linuxbin_ubuntu1804:
  stage: final
  needs: ["docker-image"]
  image: $IM
  before_script:
    - apt-get --no-install-recommends --yes install iproute2 psmisc file curl
    - apt-get install -y libglib2.0 qt5-default
    - python3 -m pip install pyinstaller
  script:
    - pyinstaller client.linux.spec
    - mv dist/PlomClient*.bin .
    - for f in PlomClient*.bin; do mv -v "$f" "${f/.bin/-ubuntu1804.bin}"; done;
    - md5sum PlomClient*.bin > md5sum
  artifacts:
    paths:
    - PlomClient*.bin
    - md5sum


# TODO: consider doing only on the master branch and only when tests pass
linuxbin_ubuntu1910:
  stage: final
  needs: []
  image: ubuntu:19.10
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata curl
    - apt-get --no-install-recommends --yes install iproute2 psmisc file binutils
      python3 python3-dev python3-wheel python3-setuptools python3-pip
    - apt-get install -y libglib2.0 qt5-default
    - pip3 install --upgrade pip
    - python3 -m pip install pyinstaller
  script:
    - python3 -m pip install -r requirements.txt.client
    - pyinstaller client.linux.spec
    - mv dist/PlomClient*.bin .
    - for f in PlomClient*.bin; do mv -v "$f" "${f/.bin/-ubuntu1910.bin}"; done;
    - md5sum PlomClient*.bin > md5sum
  artifacts:
    paths:
    - PlomClient*.bin
    - md5sum


# TODO: consider doing only on the master branch and only when tests pass
linuxbin_centos:
  stage: final
  needs: []
  image: centos:7
  before_script:
    - yum install -y dnf
    - dnf update -y
    - dnf install -y python3 python3-wheel python3-setuptools python3-pip
    # Need deps for PyQt5/Qt/plugins/platforms/libqxcb.so, others, found with `ldd`
    - dnf install -y qt5-qtbase libxkbcommon-x11 libXcomposite
    - pip3 install --upgrade pip
    - python3 -m pip install pyinstaller
  script:
    - python3 -m pip install -r requirements.txt.client
    - pyinstaller client.linux.spec
    - mv dist/PlomClient*.bin .
    - for f in PlomClient*.bin; do mv -v "$f" "${f/.bin/-centos7.bin}"; done;
    - md5sum PlomClient*.bin > md5sum
  artifacts:
    paths:
    - PlomClient*.bin
    - md5sum


.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809


winmintest:
  extends:
  - .shared_windows_runners
  stage: test
  needs: []
  script:
  - choco install -y python3
  - refreshenv
  - c:\Python38\Scripts\pip install toml
  - c:\Python38\Scripts\pip install requests-toolbelt
  - c:\Python38\Scripts\pip install pyqt5
  - refreshenv
  - echo $Env:Path
  - c:\Python38\python -m plom.scripts.client -h


# TODO: consider doing this only on the master branch
winpyinst:
  extends:
  - .shared_windows_runners
  stage: final
  needs: []
  script:
  - choco install -y python3 --version 3.7.9
  - refreshenv
  - C:\Python37\Scripts\pip install -r requirements.txt.client
  - C:\Python37\Scripts\pip install pyinstaller
  - refreshenv
  - c:\Python37\python -m plom.scripts.client -h
  - c:\Python37\Scripts\pyinstaller client.windows.spec
  - ls dist
  - move dist\PlomClient*.exe .\
  - ls
  # TODO: cannot handle the wildcard, https://gitlab.com/plom/plom/-/issues/948
  # CertUtil -hashfile PlomClient*.exe MD5 > md5sum.txt
  - ls
  artifacts:
    paths:
    - PlomClient*.exe
    # - md5sum.txt
