# SPDX-License-Identifier: FSFAP
# Copyright (C) 2022-2023 Colin B. Macdonald
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: check-toml
  - id: check-json

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
