[build-system]
requires = ["setuptools", "wheel"]

# You can run `black plom` or `black plom --verbose`
[tool.black]
line-length = 88
target-version = ['py36']
# this regexp is the default with the addition of "ui_*.py"
exclude = '/(\.eggs|\.git|\.hg|\.mypy _cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist)/|ui_.+\.py'

[tool.pylint.master]
extension-pkg-allow-list = ["PyQt5"]
generated-members = ["pandas"]
# TODO: lots of not-an-iterable in plom/db, disable for now
disable = ["E1133"]
