#  Copyright (C) 2019-2020 Andrew Rechnitzer and "Colin Macdonald"
# License "AGPL-3.0-or-later"

# >>> Edit the data below <<

# the human-readible names of the test - one long, one short.
name = "m101mt1"
longName = "Midterm for Mathematics 101"
# how many source versions
numberOfVersions = 3
# how many pages
numberOfPages = 8
# total number of papers to produce
numberToProduce=20
# how many of those papers should be named - ie from classlist - always <= numberToProduce
numberToName=10
# How many questions to mark - these will be named [question.1], [question.2], ... [question.n]
numberOfQuestions=3

# the id-pages - always taken from Version1
[idPages]
pages=[1] # must contain at least 1 page and be contiguous

# pages that are not marked (like instructions, formula sheets, examination rules etc) - always taken from Version1
[doNotMark]
pages=[2,7] # must exist, but can be an empty list.

# now the actual questions (groups of pages) to be marked
# [question.n] with n a positive integer [1,2,3... etc] - contiguous please.
# pages = [1,2,3] - contiguous ordered list of positive integers
# mark = positive integer
# select = "fixed" or "shuffle"

[question.1]
pages=[3,4]
mark=10
select="shuffle"

[question.2]
pages=[5,6]
mark=10
select="fixed"

[question.3]
pages=[8]
mark=10
select="shuffle"
