# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2019-2022 Andrew Rechnitzer
# Copyright (C) 2021-2022 Colin B. Macdonald

# Plom Client "WASD" alternative keybindings
# ------------------------------------------
#
# Many video games use "wasd" for movement of the character,
# so gamers may find this more natural than our default "esdf".
# The website http://www.use-esdf.org argues gamers should switch!
#
# Actions not overridden here will come from the default.

[next-tool]
keys = [ "e",]

[prev-tool]
keys = [ "q",]

[next-rubric]
keys = [ "s",]

[prev-rubric]
keys = [ "w",]

[next-tab]
keys = [ "d",]

[prev-tab]
keys = [ "a",]

# TODO: how to deal with alt for changeable keys?
# TODO: perhaps we want: keys and alt-keys?  Or just make two actions
[redo]
keys = [ "r", "ctrl+y",]

[undo]
keys = [ "f", "ctrl+z",]

[delete]
keys = [ "c",]

[move]
keys = [ "x",]
