name = "mabcm"
longName = "Math ABC Midterm"
numberOfPages = 6
numberOfVersions = 1
totalMarks = 20
numberOfQuestions = 3
numberToProduce = 0
idPage = 1
doNotMarkPages = [ 2, 6,]
[[questions]]
pages = [ 3,]
mark = 5
label = "Q1"
select = "fix"

[[questions]]
pages = [ 4,]
mark = 5
label = "Q2"
select = "fix"

[[questions]]
pages = [ 5,]
mark = 10
label = "Q3"
select = "fix"

