name = "plomdemo"
longName = "Midterm Demo using Plom"

numberOfVersions = 2
numberOfPages = 6
totalMarks = 20
numberOfQuestions = 3
idPage = 1
doNotMarkPages = [2]

[[question]]
label = "Q(1)"
pages = [3]
mark = 5

[[question]]
label = "Q(2)"
pages = [4]
mark = 5
select = "fix"

[[question]]
label = "Ex.3"
pages = [5, 6]
mark = 10
select = "shuffle"
